CREATE TABLE public.tasks (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	client_id bigint NOT NULL,
	subject varchar NOT NULL,
	description varchar NOT NULL,
	filing_date timestamp without time zone NOT NULL,
	completion_date timestamp without time zone NOT NULL,
	status_id bigint NOT NULL,
	executor_id bigint NULL
);

COMMENT ON TABLE public.tasks IS 'Таблица "Заявки"';

COMMENT ON COLUMN public.tasks.id IS 'Идентификатор';
COMMENT ON COLUMN public.tasks.client_id IS 'Клиент';
COMMENT ON COLUMN public.tasks.subject IS 'Тема';
COMMENT ON COLUMN public.tasks.description IS 'Описание';
COMMENT ON COLUMN public.tasks.filing_date IS 'Дата создания';
COMMENT ON COLUMN public.tasks.completion_date IS 'Дата выполнения';
COMMENT ON COLUMN public.tasks.status_id IS 'Статус заявки';
COMMENT ON COLUMN public.tasks.executor_id IS 'Исполнитель';

CREATE TABLE public.users (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username varchar NOT NULL,
	"password" varchar NOT NULL,
	credentials varchar NOT NULL,
	last_name varchar NOT NULL,
	first_name varchar NOT NULL,
	second_name varchar NOT NULL
);

COMMENT ON TABLE public.users IS 'Таблица "Пользователи"';

COMMENT ON COLUMN public.users.id IS 'Идентификатор';
COMMENT ON COLUMN public.users.username IS 'Имя пользователя';
COMMENT ON COLUMN public.users."password" IS 'Пароль';
COMMENT ON COLUMN public.users.credentials IS 'Роль';
COMMENT ON COLUMN public.users.last_name IS 'Фамилия';
COMMENT ON COLUMN public.users.first_name IS 'Имя';
COMMENT ON COLUMN public.users.second_name IS 'Отчество';

INSERT INTO public.users (username, "password", credentials, last_name, first_name, second_name) VALUES ('admin', 'admin', 'ROLE_ADMIN', 'Администратор', '-', '-');
INSERT INTO public.users (username, "password", credentials, last_name, first_name, second_name) VALUES ('kuzminem@mail.ru', 'password', 'ROLE_EXECUTOR', 'Кузьмин', 'Евгений', 'Михайлович');
INSERT INTO public.users (username, "password", credentials, last_name, first_name, second_name) VALUES ('pupkin@mail.ru', 'pupkin', 'ROLE_USER', 'Пупкин', 'Василий', 'Петрович');

CREATE TABLE public.remarks (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	task_id bigint NOT NULL,
	remark_date timestamp without time zone NOT NULL,
	remark varchar NOT NULL,
	author_id bigint NOT NULL
);

COMMENT ON TABLE public.remarks IS 'Таблица "Комментарии"';

COMMENT ON COLUMN public.remarks.id IS 'Идентификатор';
COMMENT ON COLUMN public.remarks.task_id IS 'Заявка';
COMMENT ON COLUMN public.remarks.remark_date IS 'Дата комментария';
COMMENT ON COLUMN public.remarks.remark IS 'Текст комментария';
COMMENT ON COLUMN public.remarks.author_id IS 'Автор комментария';

CREATE TABLE public.statuses (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	status varchar NOT NULL
);

COMMENT ON TABLE public.statuses IS 'Таблица "Статусы"';

COMMENT ON COLUMN public.statuses.id IS 'Идентификатор';
COMMENT ON COLUMN public.statuses.status IS 'Статус';

INSERT INTO public.statuses (status) VALUES ('Исп. не назначен');
INSERT INTO public.statuses (status) VALUES ('В работе');
INSERT INTO public.statuses (status) VALUES ('В ожидании');
INSERT INTO public.statuses (status) VALUES ('Выполнена');
